INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL_ID)
VALUES ('1','Karan', 'B','karanb@gmail.com');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL_ID)
VALUES ('2','Sahil', 'P','sahilp@gmail.com');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL_ID)
VALUES ('3','Aradhana', 'S','aradhanas@gmail.com');
INSERT INTO STUDENT (STUDENT_ID, FIRST_NAME, LAST_NAME, EMAIL_ID)
VALUES ('1','Karan', 'B','karanb@gmail.com');
INSERT INTO STUDENT (STUDENT_ID, FIRST_NAME, LAST_NAME, EMAIL_ID)
VALUES ('2','Sahil', 'P','sahilp@gmail.com');
INSERT INTO STUDENT (STUDENT_ID, FIRST_NAME, LAST_NAME, EMAIL_ID)
VALUES ('3','Aradhana', 'S','aradhanas@gmail.com');
